export const db = [{"id":1,"location":"Song’ao","min_age":5,"max_age":14,"gender":"Male"},
{"id":2,"location":"Fengshan","min_age":7,"max_age":16,"gender":"Female"},
{"id":3,"location":"Guadalupe","min_age":5,"max_age":14,"gender":"Male"},
{"id":4,"location":"Hyltebruk","min_age":4,"max_age":12,"gender":"Male"},
{"id":5,"location":"Berlin","min_age":8,"max_age":16,"gender":"Bigender"},
{"id":6,"location":"Arrap’i","min_age":4,"max_age":12,"gender":"Agender"},
{"id":7,"location":"Rājshāhi","min_age":6,"max_age":12,"gender":"Male"},
{"id":8,"location":"Sukacai","min_age":3,"max_age":15,"gender":"Male"},
{"id":9,"location":"Ban Lŭng","min_age":6,"max_age":17,"gender":"Male"},
{"id":10,"location":"Dërmënas","min_age":7,"max_age":18,"gender":"Female"},
{"id":11,"location":"Xundian","min_age":8,"max_age":17,"gender":"Male"},
{"id":12,"location":"Vila","min_age":4,"max_age":9,"gender":"Female"},
{"id":13,"location":"Arras","min_age":8,"max_age":15,"gender":"Male"},
{"id":14,"location":"Yunchi","min_age":7,"max_age":15,"gender":"Female"},
{"id":15,"location":"Valença do Piauí","min_age":8,"max_age":15,"gender":"Female"},
{"id":16,"location":"Boden","min_age":5,"max_age":9,"gender":"Female"},
{"id":17,"location":"Shangyanzhuang","min_age":5,"max_age":12,"gender":"Female"},
{"id":18,"location":"Al Fandaqūmīyah","min_age":5,"max_age":17,"gender":"Female"},
{"id":19,"location":"Maji","min_age":6,"max_age":13,"gender":"Female"},
{"id":20,"location":"Lubu","min_age":7,"max_age":11,"gender":"Female"},
{"id":21,"location":"Praia da Vitória","min_age":7,"max_age":13,"gender":"Female"},
{"id":22,"location":"Mošorin","min_age":5,"max_age":11,"gender":"Female"},
{"id":23,"location":"Szczecinek","min_age":7,"max_age":12,"gender":"Female"},
{"id":24,"location":"Cisaro","min_age":4,"max_age":12,"gender":"Male"},
{"id":25,"location":"West Jerusalem","min_age":8,"max_age":11,"gender":"Female"},
{"id":26,"location":"Ngulahan","min_age":8,"max_age":14,"gender":"Male"},
{"id":27,"location":"Itaperuna","min_age":7,"max_age":13,"gender":"Male"},
{"id":28,"location":"Chicago","min_age":4,"max_age":14,"gender":"Male"},
{"id":29,"location":"Oviedo","min_age":8,"max_age":18,"gender":"Bigender"},
{"id":30,"location":"Wu’erbu Baolige","min_age":6,"max_age":14,"gender":"Polygender"},
{"id":31,"location":"Sājir","min_age":4,"max_age":10,"gender":"Female"},
{"id":32,"location":"Pasadena","min_age":5,"max_age":13,"gender":"Female"},
{"id":33,"location":"Viso","min_age":6,"max_age":18,"gender":"Agender"},
{"id":34,"location":"El Realejo","min_age":5,"max_age":10,"gender":"Male"},
{"id":35,"location":"Bafoussam","min_age":7,"max_age":14,"gender":"Male"},
{"id":36,"location":"Asunción Mita","min_age":5,"max_age":18,"gender":"Male"},
{"id":37,"location":"Yong’an","min_age":8,"max_age":17,"gender":"Male"},
{"id":38,"location":"Guandi","min_age":5,"max_age":18,"gender":"Male"},
{"id":39,"location":"Ferreñafe","min_age":6,"max_age":10,"gender":"Male"},
{"id":40,"location":"Buaran","min_age":6,"max_age":14,"gender":"Male"},
{"id":41,"location":"Kangani","min_age":5,"max_age":10,"gender":"Female"},
{"id":42,"location":"Białobrzegi","min_age":3,"max_age":17,"gender":"Polygender"},
{"id":43,"location":"Trzemeszno","min_age":6,"max_age":13,"gender":"Male"},
{"id":44,"location":"Yulin","min_age":8,"max_age":13,"gender":"Male"},
{"id":45,"location":"Ágios Týchon","min_age":7,"max_age":11,"gender":"Female"},
{"id":46,"location":"Al Bāţinah","min_age":4,"max_age":10,"gender":"Female"},
{"id":47,"location":"São Mateus","min_age":5,"max_age":16,"gender":"Female"},
{"id":48,"location":"San Isidro","min_age":8,"max_age":18,"gender":"Female"},
{"id":49,"location":"Liuhuang","min_age":3,"max_age":15,"gender":"Female"},
{"id":50,"location":"Drammen","min_age":5,"max_age":18,"gender":"Female"},
{"id":51,"location":"Calimete","min_age":4,"max_age":17,"gender":"Female"},
{"id":52,"location":"Alfenas","min_age":5,"max_age":9,"gender":"Male"},
{"id":53,"location":"Tilamuta","min_age":6,"max_age":9,"gender":"Female"},
{"id":54,"location":"Blahodatne","min_age":5,"max_age":15,"gender":"Female"},
{"id":55,"location":"Maisons-Laffitte","min_age":7,"max_age":12,"gender":"Male"},
{"id":56,"location":"Rongmei","min_age":3,"max_age":16,"gender":"Male"},
{"id":57,"location":"Cergy-Pontoise","min_age":7,"max_age":14,"gender":"Female"},
{"id":58,"location":"Szczerbice","min_age":7,"max_age":12,"gender":"Male"},
{"id":59,"location":"San Antonio Huista","min_age":7,"max_age":12,"gender":"Male"},
{"id":60,"location":"Kronoby","min_age":6,"max_age":12,"gender":"Polygender"},
{"id":61,"location":"Bratislava","min_age":3,"max_age":10,"gender":"Male"},
{"id":62,"location":"Sŭngho 1-tong","min_age":8,"max_age":13,"gender":"Female"},
{"id":63,"location":"Castlerea","min_age":7,"max_age":11,"gender":"Male"},
{"id":64,"location":"Ouyang","min_age":6,"max_age":14,"gender":"Male"},
{"id":65,"location":"Morocelí","min_age":7,"max_age":18,"gender":"Female"},
{"id":66,"location":"Arroio Grande","min_age":3,"max_age":13,"gender":"Male"},
{"id":67,"location":"Rukunlima Bawah","min_age":7,"max_age":11,"gender":"Female"},
{"id":68,"location":"Tigaon","min_age":7,"max_age":10,"gender":"Genderqueer"},
{"id":69,"location":"Jatobá","min_age":7,"max_age":13,"gender":"Genderfluid"},
{"id":70,"location":"Yixi","min_age":3,"max_age":9,"gender":"Female"},
{"id":71,"location":"Semenivka","min_age":8,"max_age":18,"gender":"Male"},
{"id":72,"location":"Tonantins","min_age":5,"max_age":14,"gender":"Male"},
{"id":73,"location":"Timashëvsk","min_age":6,"max_age":17,"gender":"Female"},
{"id":74,"location":"Rancaranji","min_age":7,"max_age":15,"gender":"Female"},
{"id":75,"location":"Beisijia","min_age":4,"max_age":9,"gender":"Female"},
{"id":76,"location":"Choloma","min_age":4,"max_age":16,"gender":"Male"},
{"id":77,"location":"Libu","min_age":6,"max_age":17,"gender":"Female"},
{"id":78,"location":"Padang","min_age":3,"max_age":15,"gender":"Female"},
{"id":79,"location":"Tomaszów Lubelski","min_age":8,"max_age":12,"gender":"Female"},
{"id":80,"location":"Pangrumasan","min_age":3,"max_age":16,"gender":"Female"},
{"id":81,"location":"Hanušovice","min_age":3,"max_age":9,"gender":"Female"},
{"id":82,"location":"Chenhu","min_age":8,"max_age":10,"gender":"Male"},
{"id":83,"location":"Nonghe","min_age":6,"max_age":13,"gender":"Female"},
{"id":84,"location":"Presidencia Roque Sáenz Peña","min_age":5,"max_age":12,"gender":"Female"},
{"id":85,"location":"Avaré","min_age":7,"max_age":14,"gender":"Female"},
{"id":86,"location":"Gīvī","min_age":8,"max_age":18,"gender":"Female"},
{"id":87,"location":"Adelaide","min_age":6,"max_age":17,"gender":"Male"},
{"id":88,"location":"Tunjuk Selatan","min_age":7,"max_age":14,"gender":"Male"},
{"id":89,"location":"Río de Oro","min_age":8,"max_age":9,"gender":"Female"},
{"id":90,"location":"Mogok","min_age":5,"max_age":9,"gender":"Male"},
{"id":91,"location":"Beihe","min_age":7,"max_age":17,"gender":"Female"},
{"id":92,"location":"Baibu","min_age":7,"max_age":9,"gender":"Male"},
{"id":93,"location":"Gaoqiao","min_age":5,"max_age":12,"gender":"Female"},
{"id":94,"location":"Piúma","min_age":4,"max_age":10,"gender":"Polygender"},
{"id":95,"location":"Yanaoca","min_age":3,"max_age":13,"gender":"Female"},
{"id":96,"location":"Krajan Atas Suger Lor","min_age":6,"max_age":13,"gender":"Male"},
{"id":97,"location":"Pabean","min_age":7,"max_age":11,"gender":"Genderqueer"},
{"id":98,"location":"Filimonovo","min_age":4,"max_age":14,"gender":"Male"},
{"id":99,"location":"Hövsan","min_age":4,"max_age":10,"gender":"Polygender"},
{"id":100,"location":"Totness","min_age":5,"max_age":15,"gender":"Male"}]